# Generated by Django 6.0.3 on 2026-06-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autores_autor',
        ),
    ]
