# Generated by Django 6.0.3 on 2026-06-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
