# Generated by Django 6.0.3 on 2026-03-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            options={'db_table': 'tarefas_tarefa'},
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('EMPRESTADO', 'Emprestado'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateField()),
            ],
        ),
    ]
