# Generated by Django 6.0.3 on 2026-03-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='prioridade',
            field=models.CharField(choices=[('PORTUGUES', 'Português'), ('INGLES', 'Inglês')], default='PORTUGUES', max_length=20),
        ),
    ]
