# Generated by Django 6.0.3 on 2026-06-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livro_autor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livro',
            table='livros_livro',
        ),
    ]
