# Generated by Django 6.0.3 on 2026-06-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livro_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
    ]
