# Generated by Django 6.0.3 on 2026-06-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_alter_autor_options'),
        ('livros', '0006_alter_livro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='autores.autor'),
        ),
    ]
